[package]
name = "boxing-day"
description = "Unwrap a Box in festive fashion, only on boxing day!"
version = "0.1.0"
license = "MIT/X11 OR Apache-2.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
keywords = ["boxing-day", "christmas", "Box", "unwrap"]

[dependencies]
chrono = "0.4"